classifiers:
    Nearest Neighbors:
        n_neighbors: 3
        algorithm: 'auto'
    SVC:
        gamma: 2
        C: 1
        kernel: "rbf"
    MLP:
        alpha: 1
        max_iter: 1000

dataset:
    n_samples: 500
    n_features: 2
    n_redundant: 0
    n_informative: 2
    random_state: 1
    n_clusters_per_class: 1
    class_sep: 1.5
